name: Ticker Logos API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install runtime dependencies
        run: |
          python -m pip install --upgrade pip
          # Install only what the app needs according to README
          pip install fastapi uvicorn
          # Optional: if a requirements.txt is added later, install it as well
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Start server and run smoke tests
        shell: bash
        run: |
          set -euo pipefail
          # Start the FastAPI server in the background
          uvicorn main:app --host 127.0.0.1 --port 8000 &
          SERVER_PID=$!
          # Ensure the server is stopped on exit
          cleanup() { kill $SERVER_PID 2>/dev/null || true; }
          trap cleanup EXIT

          # Wait for the server to be ready
          for i in {1..30}; do
            if curl -sf http://127.0.0.1:8000/ > /dev/null; then
              break
            fi
            sleep 1
          done

          # Basic health check: root endpoint returns JSON
          curl -sf http://127.0.0.1:8000/ | python -c "import sys, json; json.load(sys.stdin); print('Root OK')"

          # /logo without query should redirect (302) to /docs
          status=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:8000/logo")
          if [ "$status" != "302" ] && [ "$status" != "307" ]; then
            echo "Expected redirect status for /logo, got $status" >&2
            exit 1
          fi

          # Expect 404 for a clearly missing ticker
          status=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:8000/logo/THIS_TICKER_SHOULD_NOT_EXIST_12345")
          if [ "$status" != "404" ]; then
            echo "Expected 404 for missing ticker, got $status" >&2
            exit 1
          fi

          echo "Smoke tests passed."
